# Generated by Django 2.2.6 on 2019-10-25 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='default_user', max_length=15)),
                ('texto', models.TextField(default='')),
                ('likes', models.IntegerField(default=0)),
                ('data_criada', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nickname', models.CharField(default='@default', max_length=15)),
                ('seguindo', models.TextField(default='')),
                ('seguidores', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='descricao',
        ),
        migrations.AddField(
            model_name='postagem',
            name='autor',
            field=models.CharField(default='default_user', max_length=15),
        ),
        migrations.AddField(
            model_name='postagem',
            name='comentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postagem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postagem',
            name='rts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postagem',
            name='texto',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
